// ============================================================================
// POST /v1/tts
//
// Server-side Text-to-Speech proxy for the desktop client. Replaces the old
// design where the shared ElevenLabs key was handed to every client via
// /v1/keys and the client called api.elevenlabs.io directly (zero moderation,
// zero rate-limiting, all traffic on one account). ElevenLabs flagged that
// account for policy-violating content generated by end users (2026-08), so
// this route:
//
//   1. Authenticates the caller (Firebase JWT via auth_middleware).
//   2. Runs the text through a fast Gemini safety classifier BEFORE any audio
//      is generated (so abusive text never reaches ElevenLabs).
//   3. Streams the ElevenLabs audio straight back to the client (true
//      passthrough via reqwest bytes_stream -> axum Body::from_stream), using a
//      server-only ElevenLabs key that is never exposed to clients.
//
// Moderation is fail-open on infrastructure errors (a Gemini timeout must not
// break TTS for everyone) but fail-closed on an explicit block verdict.
// ============================================================================

use axum::{
    body::Body,
    extract::Extension,
    http::StatusCode,
    response::{IntoResponse, Response},
    Json,
};
use serde::Deserialize;
use std::sync::Arc;
use std::time::Duration;

use crate::auth::AuthDevice;
use crate::config::Config;

const DEFAULT_VOICE_ID: &str = "EST9Ui6982FZPSi7gCHi";
const DEFAULT_MODEL_ID: &str = "eleven_multilingual_v2";
const MAX_TEXT_CHARS: usize = 5000;
const MODERATION_TIMEOUT_MS: u64 = 2500;
const ELEVENLABS_TIMEOUT_MS: u64 = 30_000;

#[derive(Deserialize)]
pub struct TtsRequest {
    pub text: String,
    #[serde(default)]
    pub voice_id: Option<String>,
    #[serde(default)]
    pub model_id: Option<String>,
    #[serde(default)]
    pub voice_settings: Option<serde_json::Value>,
    /// ElevenLabs optimize_streaming_latency (0-4). Higher = lower latency,
    /// slightly lower quality. Defaults to 3.
    #[serde(default)]
    pub optimize_streaming_latency: Option<u8>,
    /// ElevenLabs output_format, e.g. "mp3_44100_128". Optional.
    #[serde(default)]
    pub output_format: Option<String>,
}

/// POST /v1/tts — moderation-gated ElevenLabs streaming proxy.
pub async fn synthesize(
    Extension(config): Extension<Arc<Config>>,
    Extension(_auth): Extension<AuthDevice>,
    Json(req): Json<TtsRequest>,
) -> Result<Response, (StatusCode, Json<serde_json::Value>)> {
    let text = req.text.trim().to_string();
    if text.is_empty() {
        return Err(err(StatusCode::BAD_REQUEST, "empty_text", "text is required"));
    }
    if text.chars().count() > MAX_TEXT_CHARS {
        return Err(err(
            StatusCode::PAYLOAD_TOO_LARGE,
            "text_too_long",
            "text exceeds the maximum length",
        ));
    }

    // --- Moderation gate ---------------------------------------------------
    match moderate(&config, &text).await {
        ModerationVerdict::Block(reason) => {
            tracing::warn!("TTS blocked by moderation: {}", reason);
            return Err((
                StatusCode::UNPROCESSABLE_ENTITY,
                Json(serde_json::json!({
                    "error": "content_policy",
                    "reason": reason,
                })),
            ));
        }
        ModerationVerdict::Allow => {}
        ModerationVerdict::Unavailable(e) => {
            // Fail open: a moderation-infra hiccup must not break TTS globally.
            tracing::error!("TTS moderation unavailable, allowing: {}", e);
        }
    }

    // --- ElevenLabs streaming passthrough ----------------------------------
    let el_key = config.elevenlabs_proxy_api_key.trim();
    if el_key.is_empty() {
        return Err(err(
            StatusCode::INTERNAL_SERVER_ERROR,
            "not_configured",
            "TTS is not configured",
        ));
    }

    let voice_id = req
        .voice_id
        .as_deref()
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(DEFAULT_VOICE_ID);
    let model_id = req
        .model_id
        .as_deref()
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(DEFAULT_MODEL_ID);
    let latency = req.optimize_streaming_latency.unwrap_or(3).min(4);

    let mut url = format!(
        "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/stream?optimize_streaming_latency={latency}"
    );
    if let Some(fmt) = req.output_format.as_deref().filter(|s| !s.trim().is_empty()) {
        url.push_str(&format!("&output_format={fmt}"));
    }

    let voice_settings = req.voice_settings.unwrap_or_else(|| {
        serde_json::json!({
            "stability": 0.5,
            "similarity_boost": 0.75,
            "style": 0.0,
            "use_speaker_boost": true
        })
    });
    let el_body = serde_json::json!({
        "text": text,
        "model_id": model_id,
        "voice_settings": voice_settings,
    });

    let client = reqwest::Client::builder()
        .timeout(Duration::from_millis(ELEVENLABS_TIMEOUT_MS))
        .build()
        .map_err(|e| {
            err(
                StatusCode::INTERNAL_SERVER_ERROR,
                "client_build",
                &e.to_string(),
            )
        })?;

    let upstream = client
        .post(&url)
        .header("xi-api-key", el_key)
        .header("content-type", "application/json")
        .header("accept", "audio/mpeg")
        .json(&el_body)
        .send()
        .await
        .map_err(|e| err(StatusCode::BAD_GATEWAY, "upstream_error", &e.to_string()))?;

    let status = upstream.status();
    if !status.is_success() {
        let detail = upstream.text().await.unwrap_or_default();
        tracing::error!("ElevenLabs {} error: {}", status.as_u16(), detail);
        return Err((
            StatusCode::BAD_GATEWAY,
            Json(serde_json::json!({
                "error": "upstream_error",
                "status": status.as_u16(),
                "detail": detail.chars().take(500).collect::<String>(),
            })),
        ));
    }

    // Stream the audio bytes straight through as they arrive.
    let stream = upstream.bytes_stream();
    let body = Body::from_stream(stream);
    Ok(Response::builder()
        .status(StatusCode::OK)
        .header("content-type", "audio/mpeg")
        .header("cache-control", "no-store")
        .body(body)
        .unwrap()
        .into_response())
}

enum ModerationVerdict {
    Allow,
    Block(String),
    /// Moderation could not run (missing key, network error, unparseable
    /// response). Caller decides the fail-open/closed policy.
    Unavailable(String),
}

/// Fast pre-generation safety classifier using Gemini (AI Studio). Returns a
/// verdict; only genuine threats / harassment / fraud / CSAM / self-harm
/// instructions are blocked, so ordinary assistant speech is never gated.
async fn moderate(config: &Config, text: &str) -> ModerationVerdict {
    let key = config.gemini_api_key.trim();
    if key.is_empty() {
        return ModerationVerdict::Unavailable("no gemini key".to_string());
    }

    let system = "You are a content-safety classifier for a text-to-speech service. \
Block ONLY text that is a genuine threat of violence, targeted harassment, fraud/scam, \
sexual content involving minors, or explicit self-harm instructions. Ordinary, neutral, \
or merely rude text is allowed. Respond with ONLY compact JSON: \
{\"allow\":true|false,\"reason\":\"short\"}.";

    let url = format!(
        "https://generativelanguage.googleapis.com/v1beta/models/{}:generateContent?key={}",
        config.tts_moderation_model, key
    );
    let payload = serde_json::json!({
        "system_instruction": { "parts": [{ "text": system }] },
        "contents": [{ "role": "user", "parts": [{ "text": text }] }],
        "generationConfig": {
            "temperature": 0,
            "maxOutputTokens": 40,
            "responseMimeType": "application/json",
            "thinkingConfig": { "thinkingBudget": 0 }
        }
    });

    let client = match reqwest::Client::builder()
        .timeout(Duration::from_millis(MODERATION_TIMEOUT_MS))
        .build()
    {
        Ok(c) => c,
        Err(e) => return ModerationVerdict::Unavailable(e.to_string()),
    };

    let resp = match client.post(&url).json(&payload).send().await {
        Ok(r) => r,
        Err(e) => return ModerationVerdict::Unavailable(e.to_string()),
    };
    if !resp.status().is_success() {
        return ModerationVerdict::Unavailable(format!("gemini status {}", resp.status()));
    }
    let value: serde_json::Value = match resp.json().await {
        Ok(v) => v,
        Err(e) => return ModerationVerdict::Unavailable(e.to_string()),
    };

    // candidates[0].content.parts[0].text -> {"allow":bool,"reason":str}
    let raw = value
        .get("candidates")
        .and_then(|c| c.get(0))
        .and_then(|c| c.get("content"))
        .and_then(|c| c.get("parts"))
        .and_then(|p| p.get(0))
        .and_then(|p| p.get("text"))
        .and_then(|t| t.as_str());

    let raw = match raw {
        Some(s) => s.trim(),
        None => return ModerationVerdict::Unavailable("no verdict text".to_string()),
    };

    match serde_json::from_str::<serde_json::Value>(raw) {
        Ok(verdict) => {
            let allow = verdict.get("allow").and_then(|a| a.as_bool()).unwrap_or(true);
            if allow {
                ModerationVerdict::Allow
            } else {
                let reason = verdict
                    .get("reason")
                    .and_then(|r| r.as_str())
                    .unwrap_or("policy violation")
                    .to_string();
                ModerationVerdict::Block(reason)
            }
        }
        Err(e) => ModerationVerdict::Unavailable(format!("parse: {e}")),
    }
}

fn err(
    status: StatusCode,
    code: &str,
    message: &str,
) -> (StatusCode, Json<serde_json::Value>) {
    (
        status,
        Json(serde_json::json!({ "error": code, "message": message })),
    )
}
